ledger/bs2project/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^ledger/', include('ledger.urls')),
    url(r'^admin/', admin.site.urls),
]

ledger/ledger/urls.py
from django.conf.urls import url

from . import views

app_name = 'ledger'
urlpatterns =[
    url(r'^$', views.index, name='index'),
    url(r'^add_list/$', views.add_list, name='add_list'),
    url(r'^edit_list/$', views.edit_list, name='edit_list'),
    url(r'^del_list/$', views.del_list, name='del_list'),
]

ledger/ledger/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


class Note(models.Model):
    # note_text => note
    note_text = models.CharField(max_length=200)
    # cost value => income or expense
    cost_value = models.IntegerField(default=0)
    # cost_total use for display each total for each note
    cost_total = models.IntegerField(default=0)
    # pub_date => use for arranging
    pub_date = models.DateTimeField('date published')
        
    def __str__(self):
        return self.note_text
        
    

ledger/ledger/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Note

def index(request):
    # get object
    lists = Note.objects.order_by('pub_date')
    total_index = total_money()  # total money to show in index
    income_index = total_income()  # total income to show in table
    expense_index = -total_expense()  # total expense to show in table
    context = {'lists':lists,'total_index':total_index,
               'income_index':income_index,'expense_index':expense_index}
    return render(request, 'ledger/index.html',context)
    
def add_list(request):  # add note 
    # request all POST value
    new_note = request.POST['add_note']  # note's text 
    new_money = request.POST['add_money']  # money
    money_type = request.POST['money_type']  # money type (income,expense)
    time = request.POST['localtime']  # check if user wants to user timezone
    date_note = request.POST['date']  # get date from input date
    time_note = request.POST['time']  # get time from input time
    
    if time == "tz":
        time = timezone.now()
    else:
        # DatetimeField use format => dd/mm/yyyy tt:tt
        time = date_note +" "+ time_note
        
    # if money_type is expense make it minus    
    if money_type == "ex":
        new_money = -int(new_money)
    total = total_money() + int(new_money)
    
    getnote = Note(note_text=new_note,cost_value=new_money,
                   cost_total=total,pub_date=time)
    getnote.save()
    print(timezone.now())
    return HttpResponseRedirect(reverse('ledger:index'))

def edit_list(request):  # use to view edit page
    lists = Note.objects.order_by('pub_date')  # get obj. and order by date
    total_index = total_money()  # all money
    context = {'lists':lists,'total_index':total_index,}
    return render(request,'ledger/edit_page.html',context)

def del_list(request):  # delete note
    g = request.POST.getlist('note_list[]')  # get list of selected note's id
    for n in range(0,len(g)):  # use for loop to set pk for deleting
        q = Note.objects.get(pk=g[n])
        q.delete()
    # redirect to edit page
    return HttpResponseRedirect(reverse('ledger:edit_list'))
                  
def total_money():  # all money 
    total = 0  # set default to 0
    n = Note.objects.all()  # get obj.
    for note in n:  # use for loop for all note in Model
        get_money = Note.objects.get(pk=note.id)
        total += get_money.cost_value  # calculate all money
    return total 
    
def total_income():  # all income
    total = 0  # set default to 0
    n = Note.objects.all()
    for note in n:
        get_money = Note.objects.get(pk=note.id)
        if get_money.cost_value > 0:  # if variable get_money is +
            total += get_money.cost_value  # increase total value
    return total  # returnn total
    
def total_expense():  # all expense
    total = 0  # set default to 0
    n = Note.objects.all()
    for note in n:
        get_money = Note.objects.get(pk=note.id)
        if get_money.cost_value < 0:  # if variable get_money is -
            total += get_money.cost_value  # decrease total value
    return total  # # returnn total

ledger/ledger/templates/ledger/index.html
<html>
<head>
    <title>Ledger</title>
</head>
<body bgcolor="#ddfdff">
{% load humanize %}
<center><h1>Ledger</h1>
<br>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
</style>
<table bgcolor="white" style="width:80%; text-align:center;">
    <th >Date</th>
    <th>Note</th>
    <th>Income</th>
    <th>Expense</th>
    <th>Total</th>
{% if lists %}
{% for note in lists %}
<tr>
    <td>{{note.pub_date}}</td>
    <td>{{note.note_text}}</td>
    
    {% if note.cost_value < 0 %}
    <td> - </td>
    <td bgcolor="#ff9ba3">{{note.cost_value|intcomma}} Bahts</td>
    {% else %}
    <td bgcolor="#93ffbc">{{note.cost_value|intcomma}} Bahts</td>
    <td> - </td>
    {% endif %}
    
    <td>{{note.cost_total|intcomma}} Bahts</td>
</tr>

{% endfor %}
<tr>
    <td colspan="2">รวม</td>
    <td>{{income_index|intcomma}} Bahts</td>
    <td>{{expense_index|intcomma}} Bahts</td>
    <td>{{total_index|intcomma}} Bahts</td>
</tr>
{% else %}
<tr>
    <td colspan="5"><b>NOTHING TO SEE , ADD NOTE !!</b></td>
   
</tr>

{% endif %}
</table>
</center>
<br>

<b>Add note</b>
<br><br>

<form action="{% url 'ledger:add_list' %}" method="post">
{% csrf_token %}
Note : <input type="text" name="add_note" required/> Money : <input type="number" name="add_money" required/><br><br>
Date :<input type="date" name="date"> Time :<input type="time" name="time"><input type="checkbox" name="localtime" value="tz">Use timezone<br><br>
<input type="radio" name="money_type" value="in" required/>Income
<input type="radio" name="money_type" value="ex" required/>Expense<br><br>
<input type="submit" value="Submit" />
</form>

<b>Edit</b><br>
<a href="{% url 'ledger:edit_list' %}">Click</a>
</body>
</html>